# Generated by Django 4.2.30 on 2026-07-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shift_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de turno'),
        ),
    ]
