# Generated by Django 4.2.30 on 2026-07-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyconfig',
            options={'permissions': [('can_manage_company', 'Puede gestionar la configuración de empresa')], 'verbose_name': 'Configuración de Empresa', 'verbose_name_plural': 'Configuración de Empresa'},
        ),
    ]
