# Generated by Django 4.2.30 on 2026-07-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companyconfig_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='company_name',
            field=models.CharField(default='ROSARIO CAKES', max_length=200, verbose_name='Nombre de la Empresa'),
        ),
    ]
